name: validate-internal
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    # The ROM secret isn't available to pull requests from forks.
    if: github.event_name == 'push' || github.repository == github.event.pull_request.head.repo.full_name
    uses: ./.github/workflows/validate.yml
    secrets: inherit
